services:

  backend:
    build:
      context: ./backend
    container_name: cloudpulse-backend
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      AWS_DEFAULT_REGION: ap-south-1

  frontend:
    build:
      context: ./frontend
    container_name: cloudpulse-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
